config/routes.rb
Thales::Application.routes.draw do
  resources :oaipmh_records

  resources :settings, only: [ :index, :edit, :update ]

  resources :capacities

  resources :authorities

  resources :users

  resources :roles

  resources :records

  resources :schemas

  resources :properties

  resource :session
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

  match '/oaipmh' => 'oaipmh#index'

  root :to => 'records#index'

end

app/models/record.rb
# Copyright (c) 2012, The University of Queensland. (ITEE eResearch Lab)

require 'securerandom'

require_relative 'ident'

# Ruby on Rails model.

class Record < ActiveRecord::Base
  attr_accessible :uuid

  attr_accessible :ser_type
  attr_accessible :ser_data

  has_many :idents, :dependent => :destroy
  has_one :oaipmh_record

  # Sets the uuid.
  #
  # ==== Parameters
  #
  # +value+:: the value to set the uuid to, or nil to set it to a newly generated one.

  def uuid_set(value = nil)
    self.uuid = value ? value : "urn:uuid:#{SecureRandom.uuid}"
  end

  # Set the data
  #
  # ==== Parameters
  #
  # +type+:: ser_type
  # +data+:: data to set it to Thales::Datamodel::EResearch::Base

  def data_set(type, data)
    self.ser_type = type
    self.ser_data = data.serialize

    # Update the entries in the 'ident' index-table

    old_set = {}
    self.idents.each do |ident|
      old_set[ident.identifier] = ident
    end

    new_set = {}
    data.identifier.each do |identifier|
      new_set[identifier.to_s] = true
    end

    new_set.each_key do |identifier|
      if ! old_set.has_key?(identifier)
        i = Ident.new
        i.identifier = identifier.to_s
        self.idents << i
      end
    end

    old_set.each_pair do |identifier, ident|
      if ! new_set.has_key?(identifier)
        self.idents.delete(ident)
      end
    end
    
  end

  # Undo what data_set does.
  # Call this before destroying a record.

  def data_destroy
    # Remove any entries from the 'ident' index-table

    self.idents.each do |i|
      self.idents.delete(i)
    end
  end

  # Finds records by identifiers inside their data
  #
  # ==== Parameters
  #
  # +identifier+:: identifier to match
  #
  # ==== Returns
  #
  # An array of zero or more records which contain the
  # identifier as one of its identifiers.

  def self.find_by_identifier(identifier)
    matches = Ident.where(identifier: identifier)
    return matches.uniq.map { |i| i.record }
  end
end

app/controllers/records_controller.rb
# Copyright (c) 2012, The University of Queensland. (ITEE eResearch Lab)

require 'record'

# Ruby on Rails controller

class RecordsController < ApplicationController

  before_filter :authenticate

  # GET /records
  # GET /records.json
  def index

    @query = params[:q]
    if @query
      @query.lstrip!
      @query.rstrip!
      @query.downcase!
      if @query == ''
        @query = nil
      end
    end

    if @query
      # Search requested

      # TODO: replace this very inefficient placeholder
      @records = Record.all.keep_if do |record|
        match = false
        r_class = Thales::Datamodel::CLASS_FOR[record.ser_type]
        data = r_class.new.deserialize(record.ser_data)
        data.title.each do |value|
          value.downcase!
          if value.include?(@query)
            match = true
            break
          end
        end
        match
      end

    else
      # All
      @records = Record.all
    end


    @entries = @records.map do |record|
      r_class = Thales::Datamodel::CLASS_FOR[record.ser_type]
      [ record, r_class.new.deserialize(record.ser_data) ]
    end
  
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @records }
    end
  end

  # GET /records/1
  # GET /records/1.json

  def show

    @record = Record.find(params[:id])

    r_class = Thales::Datamodel::CLASS_FOR[@record.ser_type]
    @data = r_class.new.deserialize(@record.ser_data)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @data }
      format.xml { send_data @data.serialize }
      format.rifcs do
        b = Nokogiri::XML::Builder.new { |xml| @data.to_rifcs(xml) }
        send_data b.to_xml
      end
    end
  end

  NEW_TYPE = {
    'collection' => Thales::Datamodel::E_RESEARCH_COLLECTION,
    'party' => Thales::Datamodel::E_RESEARCH_PARTY,
    'activity' => Thales::Datamodel::E_RESEARCH_ACTIVITY,
    'service' => Thales::Datamodel::E_RESEARCH_SERVICE,
  }

  # GET /records/new
  # GET /records/new.json
  def new
    @record = Record.new

    @record.ser_type = NEW_TYPE[params[:type]]
    s_class = Thales::Datamodel::CLASS_FOR[@record.ser_type]
    if s_class.nil?
      s_class = Thales::Datamodel::EResearch::Collection # default
    end
    @data = s_class.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @record }
    end
  end

  # GET /records/1/edit
  def edit
    @record = Record.find(params[:id])

    r_class = Thales::Datamodel::CLASS_FOR[@record.ser_type]
    @data = r_class.new.deserialize(@record.ser_data)
  end

  # POST /records
  # POST /records.json
  def create

    @record = Record.new(params[:record])
    @record.uuid_set()

    r_class = Thales::Datamodel::CLASS_FOR[@record.ser_type]
    @record.data_set(@record.ser_type, r_class.new(params[:data]))

    if params[:oaipmh_status] == '1'
      # Publish
      @record.build_oaipmh_record(withdrawn: false)
    end

    if @record.save
      redirect_to @record, notice: 'Record was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /records/1
  # PUT /records/1.json
  def update
    @record = Record.find(params[:id])

    r_class = Thales::Datamodel::CLASS_FOR[@record.ser_type]
    @record.data_set(@record.ser_type, r_class.new(params[:data]))

    if params[:oaipmh_status] == '1'
      # Active
      if @record.oaipmh_record.nil?
        # Not yet published: make active
        @record.build_oaipmh_record(withdrawn: false)
      elsif @record.oaipmh_record.deleted?
        # Published as deleted: change to publish as active
        @record.oaipmh_record.withdrawn = false
        @record.oaipmh_record.save
      else
        # Active already
        if @record.changed?
          # Record changed: force OAI-PMH entry to have updated timestamp
          @record.oaipmh_record.updated_at = Time.now()
          @record.oaipmh_record.save
        end
      end
    elsif params[:oaipmh_status] == '-1'
      # Deleted
      if @record.oaipmh_record.nil?
        # Not yet published: leave it as unpublished
      elsif @record.oaipmh_record.deleted?
        # Published as deleted: no change needed
      else
        # Active: change to deleted
        @record.oaipmh_record.withdrawn = true
        @record.oaipmh_record.save
      end
    end

    respond_to do |format|
      if @record.update_attributes(params[:record])
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record = Record.find(params[:id])

    @record.data_destroy()

    @record.destroy

    respond_to do |format|
      format.html { redirect_to records_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/records_helper.rb
# Copyright (c) 2012, The University of Queensland. (ITEE eResearch Lab)

require_relative '../models/record'

require 'thales/datamodel'

# Ruby on Rails helper.

module RecordsHelper

  # Generates HTML to show all properties. This is useful for
  # debugging.
  #
  # ==== Parameters
  #
  # +data+:: an instance of a Thales::Datamodel::Cornerstone::Record
  #
  # ==== Returns
  #
  # HTML

  def show_all(data)
    result = content_tag(:h3) { 'All properties' }

    g_profile = {}
    data.class.profile.each do |symbol, prop_info|
      g_profile[prop_info[:gid]] = prop_info
    end

    data.property_all do |gid, values|
      result += show_property(symbol, values, g_profile[gid], gid)
    end

    return raw result
  end

  # Generates HTML for displaying a field and its value(s)
  # on the show record page.
  #
  # The values can either be a string or an array. If it is nil, nothing
  # is generated.
  #
  # ==== Parameters
  #
  # +data+:: an instance of a Thales::Datamodel::Cornerstone::Record
  # +heading+:: text to display in +h3+ tag
  # +symbols+:: zero or more symbols
  #
  # ==== Returns
  #
  # HTML to show the +heading+ followed by values from +data+
  # corresponding to the supplied +symbols+. Only +symbols+ which have
  # values are included.
  #
  # If none of the +symbols+ have values, the empty string is
  # returned. That is, the +heading+ is only shown if there are
  # values.

  def show_group(data, heading, *symbols)
    result = ''

    symbols.each do |symbol|
      values = data.send(symbol)

      if ! values.empty?
        if heading
          result += content_tag(:h3) { heading }
          heading = nil
        end
        result += show_property(symbol, values, data.class.profile[symbol])
      end

    end

    return raw result
  end

  # Generates HTML to show all the values of a single property.
  #
  # ==== Parameters
  #
  # +symbol+:: property symbol
  # +values+:: array of values
  # +prop_info+:: optional profile item defining the property.
  # +gid+:: global identifier for the property.
  #
  # ==== Returns
  #
  # HTML

  def show_property(symbol, values, prop_info = nil, gid = nil)

# TODO: what did this do?    if ! data.property_populated?(gid)
#      return nil
#    end

    text = prop_info ? prop_info[:label] : nil
    if text && ! text.blank?
      # Non-blank label exists, use it
      label = content_tag(:span) { text }
    else
      # Derive a label from the gid
      gid = prop_info ? prop_info[:gid] : (gid ? gid : '?')
      pos = gid.rindex('/')
      if ! pos.nil? && pos != gid.size - 1
        str = "? (#{ gid.slice(pos + 1, gid.size - pos - 1) })"
      else
        str = "?"
      end
      label = content_tag(:span, :title => gid.to_s) { str }
    end

    content_tag(:div, { :class => 'item' }) do
      content_tag(:dl) do
        c = ''
        first = true

        values.each do |val|

          c += content_tag(:dt) { label }

          c += content_tag(:dd, first ? { :class => 'first' } : nil) {
            SHOW_METHODS[symbol].call(val, self)
            #self.content_tag(:strong, "aaa")
          }

          first = false
        end
        raw c
      end # :dl
    end # :div
  end

  SHOW_METHODS = {}

  SHOW_METHODS[:identifier] =
    ->(value, result) {
    result.content_tag(:span, style: 'font-size: small;') { value }
  }

  SHOW_METHODS[:tag_FoR] =
    ->(val, result) {
    uri = val.uri
    display_text = val.hint
    if display_text.nil? || display_text.blank?
      display_text = uri
      if uri.start_with?(Thales::Datamodel::EResearch::Base::FOR_URI_PREFIX)
        rest = uri[Thales::Datamodel::EResearch::Base::FOR_URI_PREFIX.length..-1]
        if rest =~ /^(\d+)$/
          display_text = "<#{$~[1]}>"
        end
      end
    end
    result.content_tag(:span, :title => "FoR code: #{uri}") { display_text }
  }

  SHOW_METHODS[:tag_SEO] =
    ->(val, result) {
    uri = val.uri
    display_text = val.hint
    if display_text.nil? || display_text.blank?
      display_text = uri
      if uri.start_with?(Thales::Datamodel::EResearch::Base::SEO_URI_PREFIX)
        rest = uri[Thales::Datamodel::EResearch::Base::SEO_URI_PREFIX.length..-1]
        if rest =~ /^(\d+)$/
          display_text = "<#{$~[1]}>"
        end
      end
    end
    result.content_tag(:span, :title => "SEO code: #{uri}") { display_text }
  }

  SHOW_METHODS[:contact_email] =
    ->(value, result) {
    result.content_tag(:a, :href => "mailto:#{value}") { value }
  }

  SHOW_METHODS[:web_page] =
    ->(value, result) {
    result.content_tag(:a, :href => value) { value }
  }

  SHOW_METHODS.default =
    ->(val, result) {

    if ! val.respond_to?(:uri)
      # Text property
      return val
    end

    # Link property

    uri = val.uri
    display_text = val.hint
    if display_text.nil? || display_text.blank?
      display_text = uri
    end

    matches = Record.find_by_identifier(val.uri)
    if matches && ! matches.empty?
      # The system has record(s) with this identifier, so link to them.
      # In normal practice there would be only record, but it is possible
      # for more than one record to contain the same identifier.
      m = ''
      matches.each do |record|
        r_class = Thales::Datamodel::CLASS_FOR[record.ser_type]
        data = r_class.new.deserialize(record.ser_data)

        m += '<br/>' if m != ''
        m += result.link_to(data.display_title, record,
                            class: 'link-internal',
                            title: "Internal record: #{display_text}")
      end
      result.raw m

    else
      # No record exist in the system with this identifier, so display it
      # as an external hyperlink or as text.
      if uri.starts_with?('https://', 'http://', 'mailto:')
        # Display link as a hyperlink
        result.content_tag(:a, :href => uri,
                    class: 'link-external', title: 'External identifier') { display_text }
      else
        # Display link as non-hyperlinked text
        result.content_tag(:span, :title => val.uri,
                    :class => 'link-identifier') { display_text }
      end
    end
  }

  # Generates HTML for displaying the subtype of a record.
  #
  # ==== Parameters
  #
  # +data+:: an instance of a Thales::Datamodel::Cornerstone::Record
  #
  # ==== Returns
  #
  # HTML

  def show_subtype(data)
    result = ''
    sts = data.subtype
    if sts
      sts.each do |st|
        result += show_property(:subtype,
                                [ st[/[^\/]*\/[^\/]*$/] ],
                                { label: 'Type/subtype' })
      end
    end
    return raw result
  end

  # Generates HTML for editing the subtype.

  def form_subtype(data)
    name = :data_subtype

    if @data.instance_of? Thales::Datamodel::EResearch::Collection
      label = 'Collection subtype'
      options = [
                 ['Collection', "#{Thales::Datamodel::EResearch::Base::SUBTYPE_BASE_URI}/collection/collection"],
                 ['Dataset', "#{Thales::Datamodel::EResearch::Base::SUBTYPE_BASE_URI}/collection/dataset"],
                ]
    elsif @data.instance_of? Thales::Datamodel::EResearch::Party
      label = 'Party subtype'
      options = [
                 ['Person', "#{Thales::Datamodel::EResearch::Base::SUBTYPE_BASE_URI}/party/person"],
                 ['Group', "#{Thales::Datamodel::EResearch::Base::SUBTYPE_BASE_URI}/party/group"],
                 ['Administrative position', "#{Thales::Datamodel::EResearch::Base::SUBTYPE_BASE_URI}/party/position"],
                ]
    elsif @data.instance_of? Thales::Datamodel::EResearch::Activity
      label = 'Activity subtype'
      options = [
                 ['Project', "#{Thales::Datamodel::EResearch::Base::SUBTYPE_BASE_URI}/activity/project"],
                 ['Program', "#{Thales::Datamodel::EResearch::Base::SUBTYPE_BASE_URI}/activity/program"],
                ]
    elsif @data.instance_of? Thales::Datamodel::EResearch::Service
      label = 'Service subtype'
      options = [
                 ['Report', "#{Thales::Datamodel::EResearch::Base::SUBTYPE_BASE_URI}/service/report"],
                ]
    else
      raise 'internal error: not implemented yet'
    end
    
    content_tag(:div, { :class => 'item' }) do
      content_tag(:dl) do
        c = content_tag(:dt) do
          label_tag(name, label)
        end
        c += content_tag(:dd, { :class => 'first' }) do
          select_tag(:data_subtype,
                     options_for_select(options, data.subtype[0]),
                     name: 'data[subtype]')
        end # :dd
      end # :dl
    end # :div

  end

  # Generates HTML for editing the values of a field.
  #
  # ==== Parameters
  #
  # +data+:: an instance of a Thales::Datamodel::Cornerstone::Record
  # +heading+:: text to display in +h3+ tag
  # +symbols+:: zero or more symbols
  #
  # ==== Returns
  #
  # HTML showing the +heading+ followed by edit fields from +data+
  # corresponding to the supplied +symbols+.

  def form_group(data, heading, *symbols)
    result = content_tag(:h3) { heading }

    symbols.each do |symbol|
      result += field_prop(symbol, data.class.profile[symbol],
                           data.send(symbol))
    end

    return raw result
  end

  def field_prop(symbol, info, values)

    name_base = symbol.to_s

    name = 'data' + '[' + name_base + ']'

    maxlength = info[:maxlength]

    default_label = info[:label]
    label = (! default_label.nil?) ? default_label : symbol.to_s

    if info[:singular]
      # Fields for a non-repeating property

      if ! info[:is_link]
        # Text property
        value_str = values[0]
        placeholder = nil
      else
        # Link property
        if values[0].nil?
          value_str = ''
        else
          value_str = "#{values[0].uri} -- #{values[0].hint}"
        end
        placeholder = 'URI [display text]'
      end

      content_tag(:div, { :class => 'item' }) do
        content_tag(:dl) do

app/views/records/_form.html.erb
<div id="propertiesEdit">

<% max_short_length = 40 %>
<% max_length = 255 %>
<% max_long_length = 255 %>

<%= form_for(@record) do |f| %>

  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field(:ser_type) %>

  <% if @data.instance_of? Thales::Datamodel::EResearch::Collection %>

  <%= form_subtype(@data) %>
  <%= form_group(@data, "General information",
      :title, :title_alt, :description, :identifier) %>
  <%= form_group(@data, "Tags",
      :tag_keyword, :tag_FoR, :tag_SEO) %>
  <%= form_group(@data, "Other",
      :contact_email, :web_page) %>
  <%= form_group(@data, "Coverage",
      :temporal, :spatial_geoname, :spatial_point, :spatial_polygon, :spatial_text) %>
  <%= form_group(@data, "Rights",
      :rights_access, :rights_statement, :rights_licence) %>
  <%= form_group(@data, "Related records",
      :createdBy, :managedBy, :accessedVia, :referencedBy) %>

  <% elsif @data.instance_of? Thales::Datamodel::EResearch::Party %>

  <%= form_subtype(@data) %>
  <%= form_group(@data, "Name",
      :name_prefix, :name_given, :name_family) %>
  <%= form_group(@data, "General information",
      :title, :title_alt, :description, :identifier) %>
  <%= form_group(@data, "Tags",
      :tag_keyword, :tag_FoR, :tag_SEO) %>
  <%= form_group(@data, "Other",
      :contact_email, :web_page) %>
  <%= form_group(@data, "Related records",
      :creatorFor, :managerFor, :operatorFor, :participantIn, :authorOf) %>

  <% elsif @data.instance_of? Thales::Datamodel::EResearch::Activity %>

  <%= form_subtype(@data) %>
  <%= form_group(@data, "General information",
      :title, :title_alt, :description, :identifier) %>
  <%= form_group(@data, "Tags",
      :tag_keyword, :tag_FoR, :tag_SEO) %>
  <%= form_group(@data, "Other",
      :contact_email, :web_page) %>
  <%= form_group(@data, "Coverage",
      :temporal) %>
  <%= form_group(@data, "Related records",
      :hasParticipant, :producerFor) %>

  <% elsif @data.instance_of? Thales::Datamodel::EResearch::Service %>

  <%= form_subtype(@data) %>
  <%= form_group(@data, "General information",
      :title, :title_alt, :description, :identifier) %>
  <%= form_group(@data, "Tags",
      :tag_keyword, :tag_FoR, :tag_SEO) %>
  <%= form_group(@data, "Other",
      :contact_email, :web_page) %>
  <%= form_group(@data, "Related records",
      :operatedBy, :providesAccessTo) %>

  <% else %>
  <p>Internal error: unknown record type for form.</p>
  <% end %>

<!-- Demo of potential upload capability
<h3>Data</h3>
<div class="item" id="upload">
  <dl>
    <dt><label for="upload_file">Upload data</label></dt>
    <dd class="first"><%= file_field 'upload', 'datafile' %></dd>
  </dl>
</div>
-->

  <h3>OAI-PMH publish</h3>
  <%= form_oaipmh_status(@record) %>

  <div id="actions">
    <div class="main">
      <%= f.submit(@record.new_record? ? 'Create record' : 'Save record') %>
    </div>
    <div class="alt">
	<%=
	   if @record.new_record?
	     link_to('Cancel', records_path, class: 'buttonCancel',
	             confirm: 'Discard and do not create a new record?')
	   else
	     link_to('Cancel', @record, class: 'buttonCancel',
	             confirm: 'Discard any changes and leave record unchanged?')
	   end
	%>
    </div>
  </div>

<% end %>

</div>

app/views/records/edit.html.erb
<% content_for(:page_title) do "#{@data.display_title} (editing)" end %>
<% content_for(:page_heading) do "Editing #{Thales::Datamodel::LABEL_FOR[@record.ser_type]} record" end %>

<!-- UUID: <%= @record.uuid %> -->

<%= render 'form' %>

app/views/records/index.html.erb
<% content_for(:page_title) do "Records" end %>
<% content_for(:page_heading) do "Records" end %>

<%= search_block %>

<table id="gradient-style" summary="Results">
  <thead>
    <tr><th scope="col">
	<%= @query ? "Search results: #{@query}" : 'All Records' %>
    </th></tr>
  </thead>

  <tbody>
    <% # Output each entry as a separate row of the table
       # Sort by type and then title

       @entries.sort! do |a, b|
         r = a[0].ser_type <=> b[0].ser_type 
         r.zero? ? a[1].title <=> b[1].title : r
       end.each do |col|
         record = col[0]
         data = col[1]
       %>
    <tr>
      <td><h1><%= link_to data.display_title, record, :title => record.uuid %></h1>
	<span><%= data.description[0] %></span>
	<span class="type">
	  <%= case record.ser_type
	      when Thales::Datamodel::E_RESEARCH_COLLECTION
	      'collection'
	      when Thales::Datamodel::E_RESEARCH_PARTY
	      'party'
	      when Thales::Datamodel::E_RESEARCH_ACTIVITY
	      'activity'
	      when Thales::Datamodel::E_RESEARCH_SERVICE
	      'service'
	      else
	      'Unknown'
	      end
	      %>
	</span>
      </td>
      <%# <%= link_to 'Edit', edit_record_path(record) %>
    </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr><td><%= pluralize(@entries.size, 'record') %></td></tr>
  </tfoot>
</table>        

<!--
<p><%= link_to 'New record', new_record_path, :class => 'new' %></p>
-->

<% content_for(:navigation) { side_nav_bar(:records) } %>

app/views/records/new.html.erb
<% content_for(:page_title) do "New #{Thales::Datamodel::LABEL_FOR[@record.ser_type]} record" end %>
<% content_for(:page_heading) do "New #{Thales::Datamodel::LABEL_FOR[@record.ser_type]} record" end %>

<%= render 'form' %>

app/views/records/show.html.erb
<% content_for(:page_title) do @data.display_title end %>
<% content_for(:page_heading) do @data.display_title end %>

<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<!-- <%= @record.uuid %> -->

<div id="propertiesShow">

  <% case @record.ser_type
     when Thales::Datamodel::E_RESEARCH_COLLECTION %>
  <%= show_subtype(@data) %>
  <%= show_group(@data, "General information",
      :title, :title_alt, :description, :identifier) %>
  <%= show_group(@data, "Tags",
      :tag_keyword, :tag_FoR, :tag_SEO) %>
  <%= show_group(@data, "Other",
      :contact_email, :web_page) %>
  <%= show_group(@data, "Coverage",
      :temporal, :spatial_geoname, :spatial_point, :spatial_polygon, :spatial_text) %>
  <%= show_group(@data, "Rights",
      :rights_access, :rights_statement, :rights_licence) %>
  <%= show_group(@data, "Related records",
      :createdBy, :managedBy, :accessedVia, :referencedBy) %>

  <% when Thales::Datamodel::E_RESEARCH_PARTY %>
  <%= show_subtype(@data) %>
  <%= show_group(@data, "Name",
      :name_prefix, :name_given, :name_family) %>
  <%= show_group(@data, "General information",
      :title, :title_alt, :description, :identifier) %>
  <%= show_group(@data, "Tags",
      :tag_keyword, :tag_FoR, :tag_SEO) %>
  <%= show_group(@data, "Other",
      :contact_email, :web_page) %>
  <%= show_group(@data, "Related records",
      :creatorFor, :managerFor, :operatorFor, :participantIn, :authorOf) %>

  <% when Thales::Datamodel::E_RESEARCH_ACTIVITY %>
  <%= show_subtype(@data) %>
  <%= show_group(@data, "General information",
      :title, :title_alt, :description, :identifier) %>
  <%= show_group(@data, "Tags",
      :tag_keyword, :tag_FoR, :tag_SEO) %>
  <%= show_group(@data, "Other",
      :contact_email, :web_page) %>
  <%= show_group(@data, "Coverage",
      :temporal) %>
  <%= show_group(@data, "Related records",
      :hasParticipant, :producerFor) %>

  <% when Thales::Datamodel::E_RESEARCH_SERVICE %>
  <%= show_subtype(@data) %>
  <%= show_group(@data, "General information",
      :title, :title_alt, :description, :identifier) %>
  <%= show_group(@data, "Tags",
      :tag_keyword, :tag_FoR, :tag_SEO) %>
  <%= show_group(@data, "Other",
      :contact_email, :web_page) %>
  <%= show_group(@data, "Related records",
      :operatedBy, :providesAccessTo) %>

  <% else %>
  <p>Internal error: show view: unknown record type</p>
  <% end %>

  <%#= show_all(@data) # for debugging %>

  <div id="actions">
    <div class="main">
      <%= link_to('Edit record', edit_record_path(@record), class: 'buttonEdit') %>
    </div>
  <div class="subordinate">
    <%= link_to('Delete record', @record, method: :delete, class: 'buttonDelete',
	        confirm: 'Delete this record?') %>
  </div>

  </div>

  <%#= link_to "RIF-CS version", record_path(@record, :rifcs) %>

  <p id="status">
    OAI-PMH status:
    <%=
       oai_rec = @record.oaipmh_record
       if oai_rec.nil?
         'not published'
       else
         if oai_rec.deleted?
           'published as a deleted record'
         else
           'published'
         end
       end
       %></p>

  <p id="updatedTime" title="<%= @record.updated_at.iso8601 %>">Last updated: <%= @record.updated_at.to_s(:rfc822) %></p>
</div>


<% content_for(:navigation) { side_nav_bar(:records) } %>