config/routes.rb
Thales::Application.routes.draw do
  resources :oaipmh_records

  resources :settings, only: [ :index, :edit, :update ]

  resources :capacities

  resources :authorities

  resources :users

  resources :roles

  resources :records

  resources :schemas

  resources :properties

  resource :session
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

  match '/oaipmh' => 'oaipmh#index'

  root :to => 'records#index'

end

app/models/capacity.rb
class Capacity < ActiveRecord::Base
  attr_accessible :name, :shortname, :uuid
end

app/controllers/capacities_controller.rb
class CapacitiesController < ApplicationController
  # GET /capacities
  # GET /capacities.json
  def index
    @capacities = Capacity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @capacities }
    end
  end

  # GET /capacities/1
  # GET /capacities/1.json
  def show
    @capacity = Capacity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @capacity }
    end
  end

  # GET /capacities/new
  # GET /capacities/new.json
  def new
    @capacity = Capacity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @capacity }
    end
  end

  # GET /capacities/1/edit
  def edit
    @capacity = Capacity.find(params[:id])
  end

  # POST /capacities
  # POST /capacities.json
  def create
    @capacity = Capacity.new(params[:capacity])

    respond_to do |format|
      if @capacity.save
        format.html { redirect_to @capacity, notice: 'Capacity was successfully created.' }
        format.json { render json: @capacity, status: :created, location: @capacity }
      else
        format.html { render action: "new" }
        format.json { render json: @capacity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /capacities/1
  # PUT /capacities/1.json
  def update
    @capacity = Capacity.find(params[:id])

    respond_to do |format|
      if @capacity.update_attributes(params[:capacity])
        format.html { redirect_to @capacity, notice: 'Capacity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @capacity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /capacities/1
  # DELETE /capacities/1.json
  def destroy
    @capacity = Capacity.find(params[:id])
    @capacity.destroy

    respond_to do |format|
      format.html { redirect_to capacities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/capacities_helper.rb
module CapacitiesHelper
end

app/views/capacities/_form.html.erb
<%= form_for(@capacity) do |f| %>
  <% if @capacity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@capacity.errors.count, "error") %> prohibited this capacity from being saved:</h2>

      <ul>
      <% @capacity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uuid %><br />
    <%= f.text_field :uuid %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :shortname %><br />
    <%= f.text_field :shortname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/capacities/edit.html.erb
<h1>Editing capacity</h1>

<%= render 'form' %>

<%= link_to 'Show', @capacity %> |
<%= link_to 'Back', capacities_path %>

app/views/capacities/index.html.erb
<h1>Listing capacities</h1>

<table>
  <tr>
    <th>Uuid</th>
    <th>Name</th>
    <th>Shortname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @capacities.each do |capacity| %>
  <tr>
    <td><%= capacity.uuid %></td>
    <td><%= capacity.name %></td>
    <td><%= capacity.shortname %></td>
    <td><%= link_to 'Show', capacity %></td>
    <td><%= link_to 'Edit', edit_capacity_path(capacity) %></td>
    <td><%= link_to 'Destroy', capacity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Capacity', new_capacity_path %>

app/views/capacities/new.html.erb
<h1>New capacity</h1>

<%= render 'form' %>

<%= link_to 'Back', capacities_path %>

app/views/capacities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Uuid:</b>
  <%= @capacity.uuid %>
</p>

<p>
  <b>Name:</b>
  <%= @capacity.name %>
</p>

<p>
  <b>Shortname:</b>
  <%= @capacity.shortname %>
</p>


<%= link_to 'Edit', edit_capacity_path(@capacity) %> |
<%= link_to 'Back', capacities_path %>