config/routes.rb
Thales::Application.routes.draw do
  resources :oaipmh_records

  resources :settings, only: [ :index, :edit, :update ]

  resources :capacities

  resources :authorities

  resources :users

  resources :roles

  resources :records

  resources :schemas

  resources :properties

  resource :session
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

  match '/oaipmh' => 'oaipmh#index'

  root :to => 'records#index'

end

app/models/authority.rb
class Authority < ActiveRecord::Base
  attr_accessible :name, :shortname, :uuid
end

app/controllers/authorities_controller.rb
class AuthoritiesController < ApplicationController
  # GET /authorities
  # GET /authorities.json
  def index
    @authorities = Authority.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authorities }
    end
  end

  # GET /authorities/1
  # GET /authorities/1.json
  def show
    @authority = Authority.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @authority }
    end
  end

  # GET /authorities/new
  # GET /authorities/new.json
  def new
    @authority = Authority.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @authority }
    end
  end

  # GET /authorities/1/edit
  def edit
    @authority = Authority.find(params[:id])
  end

  # POST /authorities
  # POST /authorities.json
  def create
    @authority = Authority.new(params[:authority])
    @authority.uuid = UUID.new.generate(:compact)

    respond_to do |format|
      if @authority.save
        format.html { redirect_to @authority, notice: 'Authority was successfully created.' }
        format.json { render json: @authority, status: :created, location: @authority }
      else
        format.html { render action: "new" }
        format.json { render json: @authority.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authorities/1
  # PUT /authorities/1.json
  def update
    @authority = Authority.find(params[:id])

    respond_to do |format|
      if @authority.update_attributes(params[:authority])
        format.html { redirect_to @authority, notice: 'Authority was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @authority.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authorities/1
  # DELETE /authorities/1.json
  def destroy
    @authority = Authority.find(params[:id])
    @authority.destroy

    respond_to do |format|
      format.html { redirect_to authorities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/authorities_helper.rb
module AuthoritiesHelper
end

app/views/authorities/_form.html.erb
<%= form_for(@authority) do |f| %>
  <% if @authority.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authority.errors.count, "error") %> prohibited this authority from being saved:</h2>

      <ul>
      <% @authority.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :shortname %><br />
    <%= f.text_field :shortname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authorities/edit.html.erb
<h1>Editing authority</h1>

<%= render 'form' %>

<%= link_to 'Show', @authority %> |
<%= link_to 'Back', authorities_path %>

app/views/authorities/index.html.erb
<h1>Listing authorities</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Shortname</th>
    <th>UUID</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authorities.each do |authority| %>
  <tr>
    <td><%= authority.name %></td>
    <td><%= authority.shortname %></td>
    <td><%= authority.uuid %></td>
    <td><%= link_to 'Show', authority %></td>
    <td><%= link_to 'Edit', edit_authority_path(authority) %></td>
    <td><%= link_to 'Destroy', authority, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Authority', new_authority_path %>

app/views/authorities/new.html.erb
<h1>New authority</h1>

<%= render 'form' %>

<%= link_to 'Back', authorities_path %>

app/views/authorities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Uuid:</b>
  <%= @authority.uuid %>
</p>

<p>
  <b>Name:</b>
  <%= @authority.name %>
</p>

<p>
  <b>Shortname:</b>
  <%= @authority.shortname %>
</p>


<%= link_to 'Edit', edit_authority_path(@authority) %> |
<%= link_to 'Back', authorities_path %>