config/routes.rb
Thales::Application.routes.draw do
  resources :oaipmh_records

  resources :settings, only: [ :index, :edit, :update ]

  resources :capacities

  resources :authorities

  resources :users

  resources :roles

  resources :records

  resources :schemas

  resources :properties

  resource :session
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

  match '/oaipmh' => 'oaipmh#index'

  root :to => 'records#index'

end

app/models/schema.rb
class Schema < ActiveRecord::Base
  attr_accessible :name, :shortname, :uuid
end

app/controllers/schemas_controller.rb
class SchemasController < ApplicationController
  # GET /schemas
  # GET /schemas.json
  def index
    @schemas = Schema.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schemas }
    end
  end

  # GET /schemas/1
  # GET /schemas/1.json
  def show
    @schema = Schema.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @schema }
    end
  end

  # GET /schemas/new
  # GET /schemas/new.json
  def new
    @schema = Schema.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @schema }
    end
  end

  # GET /schemas/1/edit
  def edit
    @schema = Schema.find(params[:id])
  end

  # POST /schemas
  # POST /schemas.json
  def create
    @schema = Schema.new(params[:schema])

    respond_to do |format|
      if @schema.save
        format.html { redirect_to @schema, notice: 'Schema was successfully created.' }
        format.json { render json: @schema, status: :created, location: @schema }
      else
        format.html { render action: "new" }
        format.json { render json: @schema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schemas/1
  # PUT /schemas/1.json
  def update
    @schema = Schema.find(params[:id])

    respond_to do |format|
      if @schema.update_attributes(params[:schema])
        format.html { redirect_to @schema, notice: 'Schema was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @schema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schemas/1
  # DELETE /schemas/1.json
  def destroy
    @schema = Schema.find(params[:id])
    @schema.destroy

    respond_to do |format|
      format.html { redirect_to schemas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/schemas_helper.rb
module SchemasHelper
end

app/views/schemas/_form.html.erb
<%= form_for(@schema) do |f| %>
  <% if @schema.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schema.errors.count, "error") %> prohibited this schema from being saved:</h2>

      <ul>
      <% @schema.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uuid %><br />
    <%= f.text_field :uuid %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :shortname %><br />
    <%= f.text_field :shortname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schemas/edit.html.erb
<h1>Editing schema</h1>

<%= render 'form' %>

<%= link_to 'Show', @schema %> |
<%= link_to 'Back', schemas_path %>

app/views/schemas/index.html.erb
<h1>Listing schemas</h1>

<table>
  <tr>
    <th>Uuid</th>
    <th>Name</th>
    <th>Shortname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @schemas.each do |schema| %>
  <tr>
    <td><%= schema.uuid %></td>
    <td><%= schema.name %></td>
    <td><%= schema.shortname %></td>
    <td><%= link_to 'Show', schema %></td>
    <td><%= link_to 'Edit', edit_schema_path(schema) %></td>
    <td><%= link_to 'Destroy', schema, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Schema', new_schema_path %>

app/views/schemas/new.html.erb
<h1>New schema</h1>

<%= render 'form' %>

<%= link_to 'Back', schemas_path %>

app/views/schemas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Uuid:</b>
  <%= @schema.uuid %>
</p>

<p>
  <b>Name:</b>
  <%= @schema.name %>
</p>

<p>
  <b>Shortname:</b>
  <%= @schema.shortname %>
</p>


<%= link_to 'Edit', edit_schema_path(@schema) %> |
<%= link_to 'Back', schemas_path %>